spring:
  application:
    name: TrackerUltimate
  datasource:
    url: jdbc:sqlite:thebigdatabase.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

    hibernate:
      ddl-auto: update
    show-sql: true
